<?php
return [
    'POST_UPLOAD_DIR' => 'public/posts',
    'POST_ROOT_PATH' => 'storage/posts',
    'CATEGORY_UPLOAD_DIR' => 'public/categories',
    'CATEGORY_ROOT_PATH' => 'storage/categories',
    'BRAND_UPLOAD_DIR' => 'public/brands',
    'BRAND_ROOT_PATH' => 'storage/brands',
    'USERS_UPLOAD_DIR' => 'public/users',
    'USERS_ROOT_PATH' => 'storage/users',
    'CHAT_UPLOAD_DIR' => 'public/chats',
    'CHAT_ROOT_PATH' => 'storage/chats',
    'PAGE_UPLOAD_DIR' => 'public/pages',
    'PAGE_ROOT_PATH' => 'storage/pages',
    'TRANSACTION_PER_PAGE' => 6,
    'PRIORITY_SPECIAL_CODE' => 'categories_property',
    'DATA_PER_PAGE' => 12,
    'POST_PER_PAGE' => 10,
    'POST_PER_CATEGORY' => 12,
    'AMOUNT_POST_IN_PROFILE' => 4,
    'AMOUNT_SAVED_POST' => 4,
    'SERVICE_PER_PAGE' => 12,
    'CASSO_KEY_LENGTH' => 20,
    'CASSO_KEY_NAME' => 'SECURE_TOKEN_FOR_CASSO_HOOK',
    'PLANT_PER_PAGE' => 3,
    'PLAN_UPLOAD_DIR' => 'public/plans',
    'PLAN_PUBLIC_DIR' => 'storage/plans',
    'UUID_MAX_NUMBER_LENGTH' => 9,
    'CASSO_APIS' => [
        'CREATE_HOOK' => 'https://oauth.casso.vn/v2/webhooks',
        'SYNC' => 'https://oauth.casso.vn/v2/sync',
    ],
    'SPECIAL_CATEGORIES' => ['recent-posts', 'supported_posts'],
    'CATEGORY_PER_PAGE' => 12,
    'LIMIT_SLIDE' => 6,
    'DEFAULT_MAIL' => 'dangkhanh.dev@gmail.com',
    'DEFAULT_AVT_PATH' => 'images/user-default-avt.svg',
    'DEFAULT_FAVICON' => 'images/logo.svg',
    'LIMIT_REGISTER_PLAN_CRON' => 3,
    'DEFAULT_LOGO' => 'images/logo.png',
    'LIMIT_TRUNCATE' => 200,
    'ADMIN_PERMISSION_EXCEPT_IDS' => [2, 3, 5, 13, 14, 15],
    'MOBILE_NAV_MANAGER_FEATURE' => 'ADMIN',
    'STATUS_TYPES' => ['POST' => 0, 'PAGE' => 1],
    'POST_SORT_BY' => [
        [
            'name' => 'price',
            'title' => 'Sắp xếp theo giá',
        ],
        [
            'name' => 'brand_id',
            'title' => 'Sắp xếp theo hãng',
        ],
        [
            'name' => 'status_id',
            'title' => 'Sắp xếp theo tình trạng',
        ],
    ],
    'POST_SORT_TYPE' => [
        [
            'type' => 'ASC',
            'title' => 'Sắp xếp tăng dần',
        ],
        [
            'type' => 'DESC',
            'title' => 'Sắp xếp giảm dần',
        ],
    ],
    'POST_PRICE' => [
        [
            'id' => 1,
            'min' => 0,
            'max' => 3000000,
            'text' => 'dưới 3 triệu',
        ],
        [
            'id' => 2,
            'min' => 3000000,
            'max' => 8000000,
            'text' => '3 - 8 triệu',
        ],
        [
            'id' => 3,
            'min' => 8000000,
            'max' => 25000000,
            'text' => '8 - 25 triệu',
        ],
        [
            'id' => 4,
            'min' => 50000000,
            'max' => 100000000,
            'text' => '50 - 100 triệu',
        ],
        ['id' => 5, 'min' => 100000000, 'max' => 1000000000, 'text' => 'dưới 1 tỷ'],
        [
            'id' => 6,
            'min' => 1000000000,
            'max' => 2500000000,
            'text' => '1 tỷ - 2 tỷ 5',
        ],
        [
            'id' => 7,
            'min' => 2500000000,
            'max' => 100000000000,
            'text' => 'trên 2 tỷ 5',
        ],
    ],
    'NOTIFICATION_PER_PAGE' => 10,
    'GENDERS' => [
        'male' => 0,
        'female' => 1,
        'other' => 2,
    ],
    'ROLES' => [
        'ADMIN' => 1,
        'USER' => 2,
        'DEV' => 3,
        'PARTNER' => 4,
    ],
    'NORMAL_ROLES' => [2],
    'SPECIAL_ROLES' => [1, 3],
    'SHOW_TYPES' => [
        'UNVERIFY' => 0,
        'SHOWING' => 1,
        'SOLD' => 2,
    ],
    'URL_SCHEME_SHARE' => [
        'FACEBOOK' => 'https://www.facebook.com/sharer/sharer.php?u=',
    ],
    'SCRIPT_TAG_REGEX' => '/<script\b[^>]*>(.*?)<\/script>/is',
    'IMG_TAG_REGEX' => '/<img[^>]+>/i',
    'TRANSACTION_STATUS' => [
        'FAILED' => 0,
        'SUCCESS' => 1,
        'PENDING' => 2,
    ],
    'TRANSACTION_STATUS_TITLE_MAPPED_STATUS' => ['Thất bại', 'Thành công', 'Đang xử lý'],
    'TRANSACTION_STATUS_TEXT_CLASS_MAPPED_STATUS' => ['text-danger', 'text-success', 'text-warning'],
    'TRANSACTION_TYPE' => [
        'PAYMENT_WALLET' => 0,
        'SALE_LIMIT_WALLET' => 1,
        'GET_DEPRECIATION_SUPPORT_WALLET' => 2,
        'MEMBERSHIP' => 3,
    ],
    'WALLET_NAME_MAPPED_WITH_TRANSACTION_TYPE' => ['Ví thanh toán', 'Ví bán hàng', 'Ví nhận hỗ trợ khấu hao', 'Ví thành viên', 'Ví hạn mức hỗ trợ'],
    'WALLET_KEY_MAPPED_WITH_TRANSACTION_TYPE' => ['payment_coin', 'sale_limit', 'get_depreciation_support', 'membership_point'],
    'WALLET_PRICE_MAPPED_WITH_TRANSACTION_TYPE' => ['đm', 'đ', 'đ', 'điểm'],
    'TRANSACTION_HISTORY_VIEW_MAPPED_WITH_ID_BY_INDEX' => ['site.history.payment_history', 'site.history.sale_limit_history', 'site.history.depreciation_support', 'site.history.membership_history'],
    'TRANSACTION_ACTIONS' => ['PLUS' => 0, 'DECENT' => 1],
    'DEPOSIT_TYPES' => [
        'TRADITIONAL' => 1,
        'FROM_DEPRECIATION_SUPPORT' => 2,
    ],
    'RECEIVE_SUPPORT_TYPE' => [
        'FROM_POST' => 0,
        'FROM_TRANSFER' => 1,
        'FROM_REFERRAL_CODE' => 2,
    ],
    'SUPPORT_WALLET_TYPE' => 4,
    'STATUS_SOLD_ID' => 1,
    'POST_STATUS' => [
        'UNVERIFIED' => 0,
        'VERIFIED' => 1,
        'SOLD' => 2,
        'SOLD_OR_VERIFIED' => [1, 2],
    ],
    'OFFICIAL_TYPES' => [
        'IS_OFFICIAL' => 1,
        'UN_OFFICIAL' => 0,
    ],
    'DEFAULT_STATUS_ID' => -1,
    'USER_REFERRAL_CODE_LENGTH' => 9,
];
